# A made up story with red

print("== YOU ARE IN AN AMAZING ADVENTURE ==")
print("You will be asked a bunch of questions then we'll make you up an amazing story with YOU as the star!")
print()
name = input("Your name: ")
enemy = input("Your worst enemy's name: ")
superPower = input("Your super power: ")
print()
print("Our story begins as our hero", name, "approaches a foreboding castle...")
print("Suddenly a bolt of lightning striked the ground at the feet of", name)
print("\033[31m 'Our final battle begins!' \033[0m shouts the evil", enemy, "clearly missing the fact that", name, "has the power of", superPower, "which means they'll win quite easily")
print("The two of them lock eyes and the battle begins!")
print("The battle rages on for hours and", name, "is winning!")
print("The evil", enemy, "is getting tired and", name, "is about to win!")
print("Suddenly the evil", enemy, "pulls out a secret weapon and blasts", name, "with it!")
print("But", name, "is too powerful and the blast has no effect!")
print("The evil", enemy, "realises they are defeated and runs away!")
print("The day is saved thanks to", name, "and their amazing power of", superPower)
print("The end.")